Repository boostcampwm-2022/web32-bmNotion, pull requests merged in 2022-12, with the labels that each got.

#147 [#144] Fix: 키보드 위 아래 입력에 대한 블록 이동 버그 수정
  client/src/components/BlockContent.tsx
  client/src/components/PageComponent.tsx
Labels: front-end, fix

#150 [#149] Refactor: title 기본값 및 기본 스타일 변경
  client/src/components/PageComponent.tsx
  server/src/page/page.service.js
Labels: front-end, UI

#153 [#144] Fix: 여러줄인 block에 대한 동작 버그 수정
  client/src/components/BlockContent.tsx
  client/src/components/PageComponent.tsx
Labels: front-end, fix

#159 [#158] Feat: 옵션 버튼 모달창을 이용한 블록 삭제 기능
  client/src/components/BlockContent.tsx
  client/src/components/modal/BlockOptionModalContent.tsx
Labels: feature, front-end

#161 [#157, #160] Refactor: 블록 관련 컴포넌트 리팩토링
  client/src/components/PageComponent.tsx
  client/src/components/WorkspaceList.tsx
  client/src/components/block/BlockContent.tsx
  client/src/components/block/StyledBlockContent.tsx
  client/src/pages/MainPage.tsx
Labels: front-end, refactor

#164 [#162] Feat: jotai를 이용한 상태관리
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/PageList.tsx
  client/src/components/WorkspaceList.tsx
  client/src/components/modal/SettingModalContent.tsx
  client/src/pages/Login.tsx
  client/src/pages/MainPage.tsx
  client/src/store/userAtom.tsx
  client/src/store/workSpaceAtom.tsx
  package-lock.json
  package.json
Labels: feature, front-end, refactor

#182 [#179] Feat: 드래그로 블록 다중 선택 및 다중 블록에 대한 이벤트 구현
  client/src/components/PageComponent.tsx
  client/src/components/block/BlockContent.tsx
  client/src/components/block/StyledBlockContent.tsx
  client/src/components/modal/BlockModalContent.tsx
  client/src/components/modal/BlockModalContentType.tsx
  client/src/components/modal/BlockOptionModalContent.tsx
  client/src/components/modal/TypeChangeModalContent.tsx
  client/src/components/modal/TypeChangeModalContentType.tsx
  client/src/pages/MainPage.tsx
Labels: feature, front-end

#184 [WIP] [#177] 에디터 Enter, Back space에 대한 동작 수정
  client/src/components/PageComponent.tsx
  client/src/components/block/BlockContent.tsx
  client/src/components/block/StyledBlockContent.tsx
Labels: feature, front-end

#193 [WIP] [#183] 에디터 Enter, Back space에 대한 동작 수정
  client/src/components/PageComponent.tsx
  client/src/components/block/BlockContent.tsx
  client/src/components/block/StyledBlockContent.tsx
  client/src/pages/MainPage.tsx
Labels: feature, front-end

#198 [#183] 에디터 Enter, Back space에 대한 동작 수정
  client/src/components/PageComponent.tsx
Labels: front-end, fix

#200 [#199] Fix: drag 관련 버그 수정
  client/src/components/PageComponent.tsx
  client/src/pages/MainPage.tsx
  server/package.json
Labels: front-end, fix

#201 [#183] Fix: 에디터 Enter, Back space에 대한 동작 수정
  client/src/components/PageComponent.tsx
Labels: front-end, fix

#205 [WIP] [#202] Refactor: sidebar 고정, worklist 스타일 변경
  client/public/assets/icons/moreWorkSpace.png
  client/src/components/PageList.tsx
  client/src/components/WorkspaceList.tsx
  client/src/pages/MainPage.tsx
Labels: front-end, refactor, UI

#206 [#202] Design: Setting 모달 스타일 변경
  client/src/components/PageList.tsx
  client/src/components/WorkspaceList.tsx
  client/src/components/modal/SettingModalContent.tsx
  client/src/components/modal/TopBarModalContent.tsx
  client/src/pages/MainPage.tsx
Labels: front-end, UI

#213 [#212] FIX, Feat: 제목과 첫번째 block의 상호작용
  client/src/components/PageComponent.tsx
  client/src/components/block/BlockContent.tsx
Labels: feature, front-end, fix

#219 [#209] refactor: 블록에서 Text paste 기능 수정
  client/src/components/block/BlockContent.tsx
Labels: front-end, fix

#228 [#226] !Hotfix: null 오류 처리
  client/src/components/PageComponent.tsx
  client/src/components/block/BlockContent.tsx
Labels: front-end, fix

#232 [WIP][#231] Fix: 다른 사람이 page 수정시 caret이 초기화되는 bug 수정
  client/src/components/PageComponent.tsx
  client/src/components/block/BlockContent.tsx
Labels: front-end, fix

#233 [#230] design: 설정 모달의 사용자 초대 리스트 UI 변경
  client/src/components/modal/SettingModalContent.tsx
Labels: front-end, UI

#235 [#234] Refactor: caretPosition state에서 variable로 변경
  client/src/components/PageComponent.tsx
Labels: front-end, refactor

#247 [#231] Fix: 다른 사람이 page 수정시 caret 초기화 됨
  client/src/components/PageComponent.tsx
  client/src/components/block/BlockContent.tsx
Labels: front-end, fix

#253 [#251] Design: 드래그앤 드롭 스타일 변경
  client/src/components/PageComponent.tsx
  client/src/components/block/BlockContent.tsx
  client/src/components/block/StyledBlockContent.tsx
Labels: feature, front-end, UI

#254 [#232] Feat: 마우스 이벤트로 블럭 생성 및 수정 시 caret null 처리
  client/src/components/block/BlockContent.tsx
Labels: feature, front-end

#256 [#255] [FE] keyDown 이벤트에서 isComposing 모드시 시그널 무시
  client/src/components/PageComponent.tsx
  client/src/components/block/BlockContent.tsx
Labels: bug, front-end, fix

#261 [#260] Fix: 드래그시 offsetTop null 버그 수정
  client/src/components/block/BlockContent.tsx
  client/src/pages/MainPage.tsx
Labels: front-end, fix

#227 [#226] !Hotfix: null 오류 처리
  client/src/components/PageComponent.tsx
  client/src/components/block/BlockContent.tsx
Labels: front-end, fix

#265 [#264] fix: 드래그 컴포넌트의 블록 선택 조건 수정
  client/src/pages/MainPage.tsx
Labels: front-end, fix

#269 Dev
  client/src/components/PageComponent.tsx
  client/src/components/modal/SettingModalContent.tsx
  client/src/config/config.js
  client/src/pages/MainPage.tsx
  server/src/db/db.crud.js
  server/src/index.js
  server/src/page/page.controller.js
  server/src/page/page.service.js
  server/src/sse/sse.connect.js
Labels: bug, fix

#273 [#272] fix: 드래그 버그 수정
  client/src/components/PageComponent.tsx
  client/src/components/block/BlockContent.tsx
  client/src/components/block/StyledBlockContent.tsx
  client/src/pages/MainPage.tsx
Labels: front-end, fix

#274 Release: v1.0.2
  client/src/components/PageComponent.tsx
  client/src/components/block/BlockContent.tsx
  client/src/components/block/StyledBlockContent.tsx
  client/src/components/modal/SettingModalContent.tsx
  client/src/config/config.js
  client/src/pages/MainPage.tsx
  client/src/types/block.d.ts
  server/src/db/db.crud.js
  server/src/index.js
  server/src/main/main.router.js
  server/src/page/page.controller.js
  server/src/page/page.service.js
  server/src/workspace/workspace.service.js
Labels: bug, fix

#275 Feature/272
  client/src/components/block/BlockContent.tsx
Labels: front-end, fix

#281 [#278] fix: 블록 모달에 고유 key 추가
  client/src/components/modal/BlockModalContent.tsx
  client/src/components/modal/TypeChangeModalContent.tsx
  client/src/pages/MainPage.tsx
Labels: front-end, fix

#287 [#286] Refactor: 드래그 너비, 높이 구하는 수식 변경
  client/src/pages/MainPage.tsx
Labels: front-end, refactor
