Repository boostcampwm-2022/web32-bmNotion, pull requests merged in 2022-11, with the labels that each got.

#60 Feature/46
  server/src/db/db.crud.js
  server/src/index.js
  server/src/page/page.controller.js
  server/src/page/page.service.js
Labels: feature, back-end, refactor

#82 [#78] Feat: block 모달창 타입 항목 클릭시 스타일 변경
  client/src/components/BlockContent.tsx
  client/src/components/modal/BlockModalContent.tsx
  client/src/components/modal/BlockModalContentType.tsx
Labels: feature, front-end

#97 [WIP] [#85] Feat: block 드래그 앤 드롭 구현
  client/package-lock.json
  client/package.json
  client/src/components/BlockContent.tsx
  client/src/components/PageComponent.tsx
Labels: feature, front-end

#100 Feat: workspace list 작업
  .prettierrc.js
  client/src/components/modal/BlockModalContentType.tsx
  client/src/components/modal/Modal.tsx
  client/src/pages/Login.tsx
  client/src/pages/MainPage.tsx
  client/src/pages/Register.tsx
  server/src/auth/auth.service.js
  server/src/index.js
  server/src/workspace/workspace.controller.js
  server/src/workspace/workspace.router.js
  server/src/workspace/workspace.service.js
Labels: feature, front-end, back-end

#107 [#85] fix: 드래그앤 드롭시 내용 유지 안되는 버그 수정
  client/src/components/BlockContent.tsx
  client/src/components/PageComponent.tsx
Labels: front-end, fix

#121 [#117] Feat: Page의 title 생성 및 이벤트 처리
  client/src/components/BlockContent.tsx
  client/src/components/PageComponent.tsx
  client/src/pages/MainPage.tsx
Labels: feature, front-end

#131 [#123, #124] Feat: 페이지 로드,동기화 및 페이지 정보 전송
  client/src/components/PageComponent.tsx
  client/src/config/config.js
  client/src/utils/axios.request.ts
  server/src/page/page.service.js
Labels: feature, front-end
